twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # pointe vers votre dossier d'images
        '%kernel.project_dir%/public/img': images

when@test:
    twig:
        strict_variables: true
        form_themes: ['bootstrap_5_layout.html.twig']
